jQuery.cookie=function(b,l,i){if(arguments.length>1&&String(l)!=="[object Object]"){i=jQuery.extend({},i);if(l===null||l===void 0)i.expires=-1;if(typeof i.expires==="number"){var k=i.expires,c=i.expires=new Date;c.setDate(c.getDate()+k)}l=String(l);return document.cookie=[encodeURIComponent(b),"=",i.raw?l:encodeURIComponent(l),i.expires?"; expires="+i.expires.toUTCString():"",i.path?"; path="+i.path:"",i.domain?"; domain="+i.domain:"",i.secure?"; secure":""].join("")}i=l||{};c=i.raw?function(b){return b}:
decodeURIComponent;return(k=RegExp("(?:^|; )"+encodeURIComponent(b)+"=([^;]*)").exec(document.cookie))?c(k[1]):null};
(function(b){function l(){return function(a){if(a.jquery){var d={};d[0]=jQuery;b.map(a.jquery,function(a){var e=a[0],h=a[1],j=a[2],a=a[3];if(typeof a=="string")a=b.unsafe(a);else for(var m=0;a.length&&m<a.length;m++)a[m]=b.unsafe(a[m]);j=="call"?d[h]=d[e].apply(d[e]._obj,a):j=="attr"?(d[h]=d[e][a],d[h]?d[h]._obj=d[e]:b.debug("unrecognized")):j=="refresh"?b.refresh():b.debug("unrecognized")})}}}b.log=function(a){window.console?window.console.debug?window.console.debug(a):window.console.log&&window.console.log(a):
alert(a)};b.debug=function(a){if(b.with_default(reddit.debug,!1))return b.log(a)};b.fn.debug=function(){b.debug(b(this));return b(this)};b.redirect=function(a){window.location=a};b.fn.redirect=function(a){b(this).filter("form").find(".status").show().html("redirecting...");if(b(this).attr("target")=="_top"){for(var d=window;d!=d.parent;)d=d.parent;d.location=a}else b.redirect(a);return b(this)};b.refresh=function(){window.location.reload(!0)};b.defined=function(a){return typeof a!="undefined"};b.with_default=
function(a,d){return b.defined(a)?a:d};b.websafe=function(a){typeof a=="string"&&(a=a.replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/>/g,"&gt;").replace(/</g,"&lt;"));return a||""};b.unsafe=function(a){typeof a=="string"&&(a=a.replace(/&quot;/g,'"').replace(/&gt;/g,">").replace(/&lt;/g,"<").replace(/&amp;/g,"&"));return a||""};b.uniq=function(a,b){for(var f=[],e={},h=b?b:a.length,j=0;j<a.length&&f.length<h;j++)e[a[j]]||(e[a[j]]=!0,f.push(a[j]));return f};(function(a,d){b.fn.show=function(d,
e){b(this).trigger("onshow");return a.call(this,d,e)};b.fn.hide=function(a,e){b(this).trigger("onhide");return d.call(this,a,e)}})(b.fn.show,b.fn.hide);var i={};b.request=function(a,d,f,e,h,j,m){var c=a,g=f;if(!(rate_limit(a)||window!=window.top&&!reddit.cnameframe&&!reddit.external_frame)){if(!(g=!b.with_default(e,!1)))g=i[c]?!1:i[c]=!0;e=g;d=b.with_default(d,{});f=b.with_default(f,l(c));h=b.with_default(h,"json");typeof f!="function"&&(f=l(c));g=function(a){delete i[c];return f(a)};errorhandler_in=
b.with_default(m,function(){});m=function(a){delete i[c];return errorhandler_in(a)};j=b.with_default(j,!1);if(reddit.post_site)d.r=reddit.post_site;if(reddit.cnameframe)d.cnameframe=1;if(reddit.logged)d.uh=reddit.modhash;d.renderstyle=reddit.renderstyle;e&&b.ajax({type:j?"GET":"POST",url:"/api/"+a,data:d,success:g,error:m,dataType:h})}};rate_limit=function(){var a={vote:333,comment:5E3,ignore:0,ban:0,unban:0,assignad:0},d={},f=b.defined,e=b.with_default,h=Date;return function(b){var m=new h,c=d[b],
g=e(a[b],333);d[b]=m;return f(c)&&m-c<g}}();b.fn.vote=function(a,d,f,e){if(reddit.logged&&b(this).hasClass("arrow")){var h=b(this).hasClass("up")?1:b(this).hasClass("down")?-1:0,j=b(this).all_things_by_id(),m=j.children().not(".child").find(".arrow"),c=h==1?"up":"upmod";m.filter("."+c).removeClass(c).addClass(h==1?"upmod":"up");c=h==-1?"down":"downmod";m.filter("."+c).removeClass(c).addClass(h==-1?"downmod":"down");reddit.logged&&(j.each(function(){var a=b(this).find(".entry:first, .midcol:first");
h>0?a.addClass("likes").removeClass("dislikes unvoted"):h<0?a.addClass("dislikes").removeClass("likes unvoted"):a.addClass("unvoted").removeClass("likes dislikes")}),b.defined(e)||(e=j.filter(":first").thing_id(),a+=f?"":"-"+e,b.request("vote",{id:e,dir:h,vh:a})));d&&d(j,h)}};b.fn.show_unvotable_message=function(){b(this).thing().find(".entry:first .unvotable-message").css("display","inline-block")};b.fn.thing=function(){return this.parents(".thing:first")};b.fn.all_things_by_id=function(){return this.thing().add(b.things(this.thing_id()))};
b.fn.thing_id=function(a){var a=b.with_default(a,"thing"),d=this.hasClass("thing")?this:this.thing();a!="thing"&&(d=d.find("."+a+":first"));if(d.length)return a=b.grep(d.get(0).className.match(/\S+/g),function(a){return a.match(/^id-/)}),a.length?a[0].slice(3,a[0].length):"";return""};b.things=function(){var a=b.map(arguments,function(a){return".thing.id-"+a}).join(", ");return b(a)};b.fn.same_author=function(){var a=b(this).thing_id("author"),d=[];b(".author.id-"+a).each(function(){d.push(".thing.id-"+
b(this).thing_id())});return b(d.join(", "))};b.fn.things=function(){return this.find(b.map(arguments,function(a){return".thing.id-"+a}).join(", "))};b.listing=function(a){a=a||"";if(a.slice(0,1)=="#"||a.slice(0,1)==".")a=a.slice(1,a.length);var d=a;a.slice(0,9)!="siteTable"?d="siteTable"+(a?"_"+a:""):a=a.slice(10,a.length);var f=b("#"+d).filter(":first");f.length==0&&(f=b.things(a).find(".child").append(document.createElement("div")).children(":last").addClass("sitetable").attr("id",d));return f};
var k=function(){};b.fn.set_thing_init=function(a){k=a;b(this).find(".thing:not(.stub)").each(function(){a(this)})};b.fn.new_thing_child=function(a,d){var f=this.thing_id(),e=d?b.listing(f):this.thing().find(".child:first");return(typeof a=="string"?e.prepend(a).children(":first"):a.hide().prependTo(e).show().find('input[name="parent"]').val(f).end()).randomize_ids()};b.fn.randomize_ids=function(){var a=(Math.random()+"").split(".")[1];b(this).find("*[id]").each(function(){b(this).attr("id",b(this).attr("id")+
a)}).end().find("label").each(function(){b(this).attr("for",b(this).attr("for")+a)});return b(this)};b.fn.replace_things=function(a,d,f,e){var h=this;return b.map(a,function(a){var c=a.data,a=b(h).things(c.id);e&&(a=a.filter(".stub"));if(a.length==0){var g=b.things(c.parent);g.length&&(a=b("<div></div>"),g.find(".child:first").append(a))}a.after(b.unsafe(c.content));c=a.next();d&&(c.show().children(".midcol, .entry").hide().end().children(".child:first").html(a.children(".child:first").remove().html()).end(),
f&&(a.hide(),c.children(".midcol, .entry").show()),c.find(".rank:first").html(a.find(".rank:first").html()));f?(a.hide(),d?c.children(".midcol, .entry").show():c.show()):c.hide();a.remove();k(c);return c})};b.insert_things=function(a,d){return b.map(a,function(a){var a=a.data,e=b.listing(a.parent),e=d?e.append(b.unsafe(a.content)).children(".thing:last"):e.prepend(b.unsafe(a.content)).children(".thing:first");k(e.hide().show());return e})};b.fn.delete_table_row=function(a){var d=this.parents("tr:first").get(0),
c=this.parents("table").get(0);d?b(d).fadeOut(function(){c.deleteRow(d.rowIndex);a&&a()}):a&&a()};b.fn.insert_table_rows=function(a,d){var c=this.is("table")?this.filter("table"):this.parents("table:first");b.map(c.get(),function(e){b.map(a,function(a){var c=d;c<0&&(c=Math.max(e.rows.length+c+1,0));var c=Math.min(c,e.rows.length),f=e.insertRow(c);b(f).hide().attr("id",a.id).addClass(a.css_class);b.map(a.cells,function(a){b(f.insertCell(f.cells.length)).html(b.unsafe(a))});b(f).fadeIn()})});return this};
b.fn.captcha=function(a){var b=this.find(".capimage");a&&b.attr("src","/captcha/"+a+".png").parents("form").find('input[name="iden"]').val(a);return b};b.fn.insertAtCursor=function(a){return b(this).filter("textarea").each(function(){var d=b(this).get(0),c=d.scrollTop;if(document.selection)d.focus(),document.selection.createRange().text=a;else if(d.selectionStart){var e=d.selectionStart;d.value=d.value.substring(0,d.selectionStart)+a+d.value.substring(d.selectionEnd,d.value.length);e+=a.length;d.setSelectionRange(e,
e)}else d.value+=a;if(d.scrollHeight)d.scrollTop=c;b(this).focus()}).end()};b.fn.select_line=function(a){return b(this).filter("textarea").each(function(){var d="\n",c=1,e=0;b.browser.msie&&(d="\r",c=0,e=1);for(var d=b(this).val().split(d),h=0;h<a-1;h++)e+=d[h].length+c;h=e;a<=d.length&&(h+=d[a-1].length+c);b(this).focus();this.createTextRange?(c=this.createTextRange(),c.move("character",e),e=this.createTextRange(),e.move("character",h),c.setEndPoint("StartToEnd",e),c.select()):this.selectionStart&&
this.setSelectionRange(e,h);if(this.scrollHeight)this.scrollTop=(a-2)*(this.scrollHeight/d.length)})};b.apply_stylesheet=function(a){var d=b("head").children("link[title], style[title]").filter(":first").attr("title")||"preferred stylesheet";if(document.styleSheets[0].cssText)for(var c=document.styleSheets,e=0;e<c.length;e++){if(c[e].title==d){c[e].cssText=a;break}}else b("head").children('*[title="'+d+'"]').remove(),b("head").append("<style type='text/css' media='screen' title='"+d+"'>"+a+"</style>")};
b.rehighlight_new_comments=function(){checked=b(".comment-visits-box input:checked");checked.length>0&&highlight_new_comments(checked[0].value)};var c;b.default_cookie_domain=function(a){a&&(c=a)};var g="_";b.cookie_name_prefix=function(a){a&&(g=a+"_")};b.cookie_write=function(a){if(a.name){var d={};d.expires=a.expires;d.domain=a.domain||c;d.path=a.path||"/";var f=g+a.name,a=a.data;a===null||a==""?a=null:typeof a!="string"&&(a=JSON.stringify(a));b.cookie(f,a,d)}};b.cookie_read=function(a,d){var c=
b.cookie((d||g)+a);try{c=JSON.parse(c)}catch(e){}return{name:a,data:c}}})(jQuery);
$(function(){function b(a){if(a.substring(0,1)!="#")return"#"+a;return a}function l(){k==1?($(".arrow.up").addClass("upmod").removeClass("up"),$(".arrow.downmod").removeClass("downmod").addClass("down"),$(".entry").removeClass("dislikes").addClass("likes")):k==-1?($(".arrow.upmod").removeClass("upmod").addClass("up"),$(".arrow.down").addClass("downmod").removeClass("down"),$(".entry").addClass("dislikes").removeClass("likes")):($(".arrow.upmod").removeClass("upmod").addClass("up"),$(".arrow.downmod").removeClass("downmod").addClass("down"),
$(".entry").removeClass("dislikes").removeClass("likes"))}function i(a,b,d){var c="http://www.reddit.com";b&&(c+="/r/"+b);c+="/submit?url="+encodeURIComponent(a);d&&(c+="&title="+encodeURIComponent(d));return c}reddit.external_frame=!0;var k=null;$(".arrow.up").click(function(){k=$(this).hasClass("up")?1:0;l()});$(".arrow.down").click(function(){k=$(this).hasClass("down")?-1:0;l()});var c=document.location.search;c&&c.substring(0,1)=="?"&&(c=c.slice(1,c.length));var g={};$.map(c.split("&"),function(a){a=
$.map(a.split("="),function(a){return $.websafe(decodeURIComponent(a))});g[a[0]]=a[1]});$("a").attr("href",i(g.url,g.sr,g.title));g.bgcolor&&$("body").css("background-color",b(g.bgcolor));g.bordercolor&&$(".blog").css("border-color",b(g.bordercolor));var a=g.newwindow?"_blank":"_top";$("a").attr("target",a);var d=function(){var b=i(g.url,g.sr,g.title);$(".score:visible").fadeOut(function(){$(".score").html('<a class="submit" target="'+a+'" href="'+b+'">submit</a>');$(this).fadeIn().css("display",
"")});$(".bling a, a.bling").attr("href",b);$(".arrow").each(function(){$(this).get(0).onclick=function(){a=="_blank"?window.open(b,a):window.parent.location=b}})},c={type:"GET",url:null,data:{},success:function(a){try{var b=a.data.modhash;if(b)reddit.logged=!0,reddit.modhash=b;var c=a.data.children[0].data,a=function(a){return $(".score:visible").fadeOut(function(){a();$(this).fadeIn().css("display","")})};$(".thing").addClass("id-"+c.name);$(".bling a, a.bling").attr("href","http://www.reddit.com"+
c.permalink);c.likes?(real_state=1,a(function(){$(".score.likes").html(point_label(c.score));$(".score.unvoted").html(point_label(c.score-1));$(".score.dislikes").html(point_label(c.score-2))})):c.likes==!1?(real_state=-1,a(function(){$(".score.likes").html(point_label(c.score+2));$(".score.unvoted").html(point_label(c.score+1));$(".score.dislikes").html(point_label(c.score))})):(real_state=0,a(function(){$(".score.likes").html(point_label(c.score+1));$(".score.unvoted").html(point_label(c.score));
$(".score.dislikes").html(point_label(c.score-1))}));$(".arrow").unbind("click").click(function(){$(this).vote("",set_score,!0)});reddit.logged&&k!=real_state&&(k!=null?$.request("vote",{id:c.name,dir:k}):k=real_state);l();finalize_thing(c)}catch(f){d()}},error:d},f="/button_info.json";g.sr&&(f="/r/"+g.sr+f);$.cookie_read("session","reddit_").data?(c.url=f,c.dataType="json"):(c.url=("https:"==document.location.protocol?"https://ssl.reddit.com":"http://buttons.reddit.com")+f,c.dataType=c.jsonp="jsonp",
c.jsonpCallback="buttonInfoCb",c.cache=!0);if($.defined(g.url))c.data.url=g.url;if($.defined(g.id))c.data.id=g.id;$.ajax(c)});function point_label(b){return b}function set_score(){}function finalize_thing(){};
