(function(){var a=this;function f(c,b){var d=c.split("."),e=a;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d.length&&(g=d.shift());)!d.length&&b!==void 0?e[g]=b:e=e[g]?e[g]:e[g]={}}var h=h||{};h.c=h.c||{};h.c.X=function(){for(var c=h.b.j,b=document.cookie.split(";"),d=0;d<b.length;d++){for(var e=b[d];e.charAt(0)==" ";)e=e.substring(1,e.length);if(e.indexOf(c+"=")==0)return e.substring((c+"=").length,e.length)}return null};h.c.Z=function(){document.cookie=h.b.j+"="+h.b.o+"; path=/; domain=.shareaholic.com; expires=Fri, 01-Jan-2038 00:00:01 GMT"};
h.c.H=function(){document.cookie=h.b.j+"=; path=/; domain=.shareaholic.com; expires=Thu, 01-Jan-1970 00:00:01 GMT"};h=h||{};h.b=h.b||{};h.b.j="c_id";h.b.o="00000000-0000-0000-0000-000000000000";h.b.U=function(){h.b.l()||h.c.H()};h.b.V=function(){h.c.Z()};h.b.l=function(){return h.c.X()!=h.b.o};h=h||{};h.a=h.a||{};h.a.t="d.shareaholic.com";h.a.u="/dough";h.a.v="1.0";h.a.n=top.location.protocol+"//"+h.a.t+h.a.u+"/"+h.a.v+"/";h.a.r="oven/";h.a.s="tag.gif/";h.a.p="shr_oven";h.a.g="key";h.a.i="value";
h.a.h="type";h.a.z="tags_count";h.a.w="api_key";h.a.m="shr_api_caller";h.a.A="page";h.a.B="user";h.a.f=h.a.f||[];h.a.k=h.a.k||"";h.a.Y=function(c){h.a.k=c};h.a.q=function(c,b,d){var e={};e[h.a.g]=c.toString();e[h.a.i]=b.toString();e[h.a.h]=d.toString();h.a.f.push(e)};h.a.D=function(c,b){h.a.q(c,b,h.a.A)};h.a.F=function(c,b){h.a.q(c,b,h.a.B)};
h.a.push=function(){for(var c="",b=0;h.a.f.length>0;){b++;var d=h.a.f.shift();c.length>0&&(c+="&");c+=h.a.g+b.toString()+"="+encodeURIComponent(d[h.a.g]);c+="&";c+=h.a.i+b.toString()+"="+encodeURIComponent(d[h.a.i]);c+="&";c+=h.a.h+b.toString()+"="+encodeURIComponent(d[h.a.h])}(d=document.getElementById(h.a.m))&&(d.removeNode?d.removeNode(!0):d.parentNode.removeChild(d));if(b>0){d=document.createElement("img");d.setAttribute("id",h.a.m);var e=h.a.n+h.a.s+"?";e+=h.a.w+"="+encodeURIComponent(h.a.k)+
"&"+h.a.z+"="+b+"&tags="+encodeURIComponent(c);d.setAttribute("src",e);d.style.display="none";document.body.appendChild(d)}};f("SHR.Tagging.setAccount",h.a.Y);f("SHR.Tagging.addPageTag",h.a.D);f("SHR.Tagging.addUserTag",h.a.F);f("SHR.Tagging.push",h.a.push);h.a.P=function(){h.b.l()&&document.getElementById(h.a.p)==void 0&&h.a.G()};h.a.W=function(){h.a.C(function(){h.a.P()})};h.a.C=function(c){var b=window.onload;window.onload=typeof window.onload!="function"?c:function(){b&&b();c()}};
__shr_dough_args={};h.a.O=function(){var c="",b;for(b in __shr_dough_args)c+=(c.length>0?"&":"?")+encodeURIComponent(b.toString())+"="+encodeURIComponent(__shr_dough_args[b].toString());return c};
h.a.d=function(c){var b=document.getElementsByTagName("meta");if(b)for(var d=0;d<b.length;d++){if(b[d].attributes.name&&b[d].attributes.name.value.toLowerCase()==c&&b[d].attributes.content)return b[d].attributes.content.value.toLowerCase();if(b[d].attributes.property&&b[d].attributes.property.value.toLowerCase()==c&&b[d].attributes.content)return b[d].attributes.content.value.toLowerCase()}return""};
h.a.R=function(){if(h.a.d("generator").indexOf("drupal")>=0)return!0;var c=document.getElementsByTagName("script");if(c)for(var b=0;b<c.length;b++)if(c[b].attributes.src&&c[b].attributes.src.value.toLowerCase().indexOf("drupal.js")>=0)return!0;return!1};h.a.Q=function(){return h.a.d("generator").indexOf("blogger")>=0?!0:!1};
h.a.T=function(){if(h.a.d("generator").indexOf("wordpress")>=0)return!0;var c=document.getElementsByTagName("link");if(c)for(var b=0;b<c.length;b++)if(c[b].attributes.rel&&c[b].attributes.rel.value.toLowerCase()=="stylesheet"&&c[b].attributes.href&&c[b].attributes.href.value.toLowerCase().indexOf("wp-content")>=0)return!0;return!1};h.a.S=function(){return h.a.d("og:type").indexOf("tumblr-feed:tumblelog")>=0?!0:document.getElementById("tumblr_controls")?!0:!1};
h.a.J=function(){return h.a.T()?"wordpress":h.a.S()?"tumblr":h.a.Q()?"blogger":h.a.R()?"drupal":"website"};h.a.e=function(c){if(typeof _shr!="undefined")for(var b=0;b<_shr.length;b++)if(_shr[b][0]==c)return _shr[b][1];return null};h.a.N=function(){typeof SHRSB_Settings!="undefined"&&(__shr_dough_args.sb=1);if(settings=h.a.e("SHR_SB_Settings"))__shr_dough_args.sb=1};
h.a.I=function(){typeof SHRCB_Settings!="undefined"&&(__shr_dough_args.cb=1);if(settings=h.a.e("SHR_CB_Settings"))__shr_dough_args.cb=1};h.a.M=function(){typeof SHRSS_Settings!="undefined"&&(__shr_dough_args.ss=1);if(settings=h.a.e("SHR_SS_Settings"))__shr_dough_args.ss=1};h.a.L=function(){typeof SHRRD_Settings!="undefined"&&(__shr_dough_args.rd=1);if(settings=h.a.e("SHR_RD_Settings"))__shr_dough_args.rd=1};h.a.K=function(){h.a.N();h.a.I();h.a.M();h.a.L()};
h.a.G=function(){__shr_dough_args.referrer=top.document.referrer;__shr_dough_args.platform=h.a.J();h.a.K();var c=document.createElement("iframe");c.setAttribute("id",h.a.p);var b=h.a.n+h.a.r;b+=h.a.O();c.setAttribute("src",b);c.style.display="none";document.body.appendChild(c)};f("SHR.Privacy.optIn",h.b.U);f("SHR.Privacy.optOut",h.b.V);f("SHR.Privacy.isOptedIn",h.b.l);h.a.W();})();
